### ISSUE TITLE
unknown field 'Cloneflags' in struct literal of type syscall.SysProcAttr

### ISSUE THREAD

**Issue by punalpatel** [lizrice/containers-from-scratch#1]
go get github.com/lizrice/containers-from-scratch                                                1 ↵  978  15:29:12
# github.com/lizrice/containers-from-scratch
go/src/github.com/lizrice/containers-from-scratch/main.go:33: unknown field 'Cloneflags' in struct literal of type syscall.SysProcAttr
go/src/github.com/lizrice/containers-from-scratch/main.go:49: undefined: syscall.Sethostname
go/src/github.com/lizrice/containers-from-scratch/main.go:52: undefined: syscall.Mount
go/src/github.com/lizrice/containers-from-scratch/main.go:53: undefined: syscall.Mount

**Comment by lizrice** [comment]
Sorry, I don't know how I missed this. You need to build with GOOS=linux. I should add that to the README

**Comment by Lucier2603** [comment]
I work on Mac with GoLand. And set GOOS=linux. But still got this error. Is there somewhere else I have to set?

**Comment by lizrice** [comment]
I'm afraid I'm not familiar with GoLand, but you should have these defined OK in the Linux version of syscall. What version of Go are you using?

**Comment by Lucier2603** [comment]
I use Go 1.9. It work fine on Linux.

**Comment by Lucier2603** [comment]
I use Go 1.9. It works fine in Linux.
I guess it is mac that causes the error?  Mac OS does not support those sys flags although I set GOOS=Linux.

**Comment by jebuscraisp** [comment]
Anyone has any clue on how to get the flags set for mac OS?

**Comment by derekbassett** [comment]
@Lucier2603 If you put `// +build linux` before the `package main` 
like so:
```
// +build linux

package main
```  
GoLand will stop reporting the error.
Given that this must be built in Linux anyway it really doesn't matter.

**Comment by ludwigmuench** [comment]
For anyone getting errors with VS Code on macOS: you have to add `"go.toolsEnvVars": {"GOOS" : "linux"},` to `settings.json` and restart the editor.

**Comment by neerajjain92** [comment]
@ludwigmuench Doesn't work on mac

**Comment by m1n9o** [comment]
If you use IDEA, go to Languages & Frameworks->Go->Build Tags Vendoring to set OS as linux.
