### ISSUE TITLE
panic on ubuntu 16.04 ARMv8

### ISSUE THREAD

**Issue by mattdinhnguyen** [lizrice/containers-from-scratch#2]
$ go version
go version go1.6.2 linux/arm64

ubuntu@tegra-ubuntu:containers-from-scratch$ go run main.go run echo hello
Running [echo hello] 
panic: fork/exec /proc/self/exe: operation not permitted

goroutine 1 [running]:
panic(0x1135c0, 0x482007c0f0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x384
main.must(0x7fad349028, 0x482007c0f0)
	/home/ubuntu/go/src/github.com/lizrice/containers-from-scratch/main.go:73 +0x5c
main.run()
	/home/ubuntu/go/src/github.com/lizrice/containers-from-scratch/main.go:36 +0x4ac
main.main()
	/home/ubuntu/go/src/github.com/lizrice/containers-from-scratch/main.go:17 +0x90
exit status 2
ubuntu@tegra-ubuntu:containers-from-scratch$ ps
  PID TTY          TIME CMD
28732 pts/2    00:00:00 bash
29668 pts/2    00:00:00 ps
ubuntu@tegra-ubuntu:containers-from-scratch$ /proc/self/exe
ubuntu@tegra-ubuntu:containers-from-scratch$ ps
  PID TTY          TIME CMD
28732 pts/2    00:00:00 bash
29671 pts/2    00:00:00 exe
29681 pts/2    00:00:00 ps

**Comment by lizrice** [comment]
You need to be running as root

**Comment by lizrice** [comment]
I'm closing assuming it works OK under root, but please comment again if that wasn't the issue
